# Generated by Django 5.2.8 on 2025-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=100, verbose_name='Nama Perusahaan')),
                ('nama_penanggung_jawab', models.CharField(max_length=100, verbose_name='Nama Penanggung Jawab')),
                ('jenis_biji', models.CharField(max_length=100, verbose_name='Jenis Biji Kopi')),
                ('asal_biji', models.CharField(max_length=100, verbose_name='Asal Biji Kopi')),
                ('alamat', models.TextField(verbose_name='Alamat Supplier')),
                ('kontak', models.CharField(max_length=20, verbose_name='Nomor Kontak')),
                ('tanggal_kerjasama', models.DateField(auto_now_add=True, verbose_name='Tanggal Mulai Kerjasama')),
            ],
        ),
    ]
