# Generated by Django 5.2.8 on 2025-11-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='Nama Barista')),
                ('no_telepon', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('shift', models.CharField(max_length=50, verbose_name='Shift Kerja')),
                ('tanggal_mulai', models.DateField(auto_now_add=True, verbose_name='Tanggal Mulai Bekerja')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('no_telepon', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('alamat', models.TextField(verbose_name='Alamat Tinggal')),
                ('tanggal_daftar', models.DateField(auto_now_add=True, verbose_name='Tanggal Daftar')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=200)),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=10)),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
                ('barista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='supplier.barista')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='supplier.customer')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='supplier.supplier')),
            ],
        ),
    ]
