# Generated by Django 5.2.8 on 2025-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_barista_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barista',
            name='shift',
            field=models.CharField(choices=[('PAGI', 'Pagi'), ('SIANG', 'Siang'), ('MALAM', 'Malam')], default='PAGI', max_length=50),
        ),
    ]
