# Generated by Django 5.2.8 on 2025-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_barista_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='tanggal_kerjasama',
            new_name='tanggal_registrasi',
        ),
    ]
